maint/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('partserver/', include('partserver.urls')),
    path('', RedirectView.as_view(url='partserver/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partserver/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'partserver'
urlpatterns = [
	path('', views.index, name='index'),
	path('lines/<int:pk>', views.LineDetailView.as_view(), name='line-detail'),
	path('parts/', views.PartListView.as_view(), name='parts'),
	path('parts/<int:pk>', views.PartDetailView.as_view(), name='part-detail'),
	path('part/create/', views.PartCreate.as_view(), name='part_create'),
    path('part/<int:pk>/update/', views.PartUpdate.as_view(), name='part_update'),
    path('part/<int:pk>/delete/', views.PartDelete.as_view(), name='part_delete'),
    path('schematics/', views.SchematicListView.as_view(), name='schematics'),
	path('schematic/create/', views.SchematicCreate.as_view(), name='schematic_create'),
	path('schematic/<int:pk>/update/', views.SchematicUpdate.as_view(), name='schematic_update'),
	path('schematic/<int:pk>/delete/', views.SchematicDelete.as_view(), name='schematic_delete'),
	path('manuals/', views.ManualListView.as_view(), name='manuals'),
	path('manual/create/', views.ManualCreate.as_view(), name='manual_create'),
	path('manual/<int:pk>/update/', views.ManualUpdate.as_view(), name='manual_update'),
	path('manual/<int:pk>/delete/', views.ManualDelete.as_view(), name='manual_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partserver/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.template.defaultfilters import slugify
import uuid
from django.db.models.signals import post_delete
from django.dispatch import receiver
from .validators import validate_file_extension
import os

def get_image_filename(instance, filename):
    name = instance.part.name
    slug = slugify(name)
    return "part_images/%s-%s" % (slug, filename)  

def get_schematic_filename(instance, filename):
	name = instance.name
	line = instance.line.name
	section = instance.section.name
	slug = slugify(name)
	ext = os.path.splitext(filename)[1]
	return "schematics/%s/%s/%s%s" % (line, section, slug, ext)

def get_manual_filename(instance, filename):
	name = instance.name
	line = instance.line.name
	section = instance.section.name
	slug = slugify(name)
	ext = os.path.splitext(filename)[1]
	return "manual/%s/%s/%s%s" % (line, section, slug, ext)

class Section(models.Model):
	"""Model representing the section of line."""
	name = models.CharField(max_length=30, help_text='Enter the section for the line')

	def __str__(self):
		"""String for representing the Model object."""
		return self.name

class Part(models.Model):
	#module representing the part
	name = models.CharField(max_length=100, help_text='Enter the part\'s name')
	number = models.CharField(max_length=20, help_text='Enter the part\'s number')
	quantity = models.PositiveIntegerField(blank=True, null=True, help_text='Part\'s in stock quantity')
	specs = models.TextField(max_length=1000, help_text='Enter the specification of the part')
	lines = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied lines for the part')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section(s) for this part')

	class Meta:
		ordering = ['name']

	def __str__(self):
		"""String for representing the Model object."""
		return self.name + " - " + self.number
    
	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('partserver:part-detail', args=[str(self.id)])

	def get_images(request):
		images = PartImages.objects.filter(part=request).values_list('images', flat=True)
		return images

	def get_specs(self):
		return self.specs.split("\n")

class Schematic(models.Model):
	name = models.CharField(max_length=100, help_text='Enter the schematic\'s name')
	line = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied line for the schematic')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section for the schematic')
	pdfFile = models.FileField(upload_to=get_schematic_filename, validators=[validate_file_extension])

class Manual(models.Model):
	name = models.CharField(max_length=100, help_text='Enter the manual\'s name')
	line = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied line for the manual')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section for the manual')
	pdfFile = models.FileField(upload_to=get_manual_filename, validators=[validate_file_extension])


class Line(models.Model):
	#name for the line(s)
	name = models.CharField(max_length=50, help_text='Enter the line(s)')
	section = models.ManyToManyField(Section, help_text='Select the section(s) for this line')

	class Meta:
		ordering = ['id']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('partserver:line-detail', args=[str(self.id)])

	def display_section(self):
		"""Create a string for the Section in Admin."""
		return ', '.join(section.name for section in self.section.all())

class PartImages(models.Model):
    """Images for a model"""
    part = models.ForeignKey(
        Part,
        null=False,
        on_delete=models.CASCADE,
        related_name='images',
        )

    images = models.ImageField(
        verbose_name='images',
        upload_to=get_image_filename,
    )

@receiver(post_delete, sender=PartImages)
def submission_delete(sender, instance, **kwargs):
    instance.images.delete(False) 

@receiver(post_delete, sender=Schematic)
def submission_delete(sender, instance, **kwargs):
    instance.pdfFile.delete(False) 

@receiver(post_delete, sender=Manual)
def submission_delete(sender, instance, **kwargs):
    instance.pdfFile.delete(False) 

partserver/views.py
from django.shortcuts import render
from .models import Part, Section, Line, PartImages, Schematic, Manual
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import qrcode
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory
from django.db.models import Q

def index(request):
	"""View function for home page of site."""

	# Generate counts of some of the main objects
	part_list = Part.objects.all()
	num_parts = part_list.count()
	line_list = Line.objects.all()
	section_list = Section.objects.all()
	context = {
		'num_parts': num_parts,
		'line_list': line_list,
		'section_list': section_list,
	}

	# Render the HTML template index.html with the data in the context variable
	return render(request, 'index.html', context=context)

class LineDetailView(generic.DetailView):
	model = Line
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(LineDetailView, self).get_context_data(**kwargs)
		context['part_list'] = Part.objects.all()
		return context

class PartListView(generic.ListView):
	model = Part
	paginate_by = 30
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(PartListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		context['section_list'] = Section.objects.all()
		context['num_parts'] = self.get_queryset().count()
		return context
	def get_queryset(self):
		querydetail = self.request.GET.get('detail')
		querysection = self.request.GET.get('section')
		queryline = self.request.GET.get('line')
		FilteredParts = Part.objects.all()
		if queryline:
			FilteredParts = Part.objects.filter(lines=Line.objects.get(pk=queryline))
		if querysection:	
			FilteredParts = FilteredParts.filter(section=Section.objects.get(id=querysection))
		FilteredParts = FilteredParts.filter(Q(name__icontains=querydetail) |
								   Q(number__icontains=querydetail) | 
								   Q(specs__icontains=querydetail))
		

		return FilteredParts

class PartDetailView(generic.DetailView):
	model = Part
	def part_detail_view(request, primary_key):
		try:
			part = part.objects.get(pk=primary_key)

		except Part.DoesNotExist:
			raise Http404('Part does not exist')

		return render(request, 'partserver/part_detail.html', context={'part': part})

class SchematicListView(generic.ListView):
	model = Schematic
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(SchematicListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		return context

class ManualListView(generic.ListView):
	model = Manual
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(ManualListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		return context

class PartImagesInline(InlineFormSetFactory):
	model = PartImages
	fields = '__all__'

class PartCreate(LoginRequiredMixin, CreateWithInlinesView):
	model = Part
	inlines = [PartImagesInline]
	fields = ['name', 'number', 'specs', 'lines', 'section']

class PartUpdate(LoginRequiredMixin, UpdateWithInlinesView):
	model = Part
	inlines = [PartImagesInline]
	fields = ['name', 'number', 'specs', 'lines', 'section']

class PartDelete(LoginRequiredMixin, DeleteView):
	model = Part
	success_url = reverse_lazy('index')

class SchematicCreate(LoginRequiredMixin, CreateView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class SchematicUpdate(LoginRequiredMixin, UpdateView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class SchematicDelete(LoginRequiredMixin, DeleteView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class ManualCreate(LoginRequiredMixin, CreateView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

class ManualUpdate(LoginRequiredMixin, UpdateView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

class ManualDelete(LoginRequiredMixin, DeleteView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

partserver/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  <title>CFP Parts Server</title>
  {% load static %}
  <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
      summary {
        list-style: none;
      }
      details>summary::marker {
        display:none;
      }
  </style>
  <script type="text/javascript" src="{% static 'js/qrcode.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/qrious.js' %}"></script>
</head>
<body class="bg-dark" onload="startTime()">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarCollapse">
      {% block navbar-nav %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item mr-2 border-bottom">
          <a class="nav-link text-success" href="{% url 'partserver:index' %}">Home</a>
        </li>
        <li class="nav-item  mr-2 border-bottom">
          <a class="nav-link text-success" href="{% url 'partserver:schematics' %}">Schematic</a>
        </li>
        <li class="nav-item  mr-2 border-bottom">
          <a class="nav-link text-success" href="{% url 'partserver:manuals' %}">Manual</a>
        </li>
      </ul>
      {% endblock %}
      {% if user.is_authenticated %}
        <div>
          <span class="dropdown">
            <button class="btn btn-primary dropdown-toggle mx-2" type="button" id="uploadMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Upload
            </button>
            <div class="dropdown-menu text-center" aria-labelledby="uploadMenuButton">
              <a class="dropdown-item text-info" href="{% url 'partserver:part_create'%}?next={{request.path}}">Part</a>
              <a class="dropdown-item text-info" href="{% url 'partserver:schematic_create'%}?next={{request.path}}">Schematic</a>
              <a class="dropdown-item text-info" href="{% url 'partserver:manual_create'%}?next={{request.path}}">Manual</a>
            </div>
          </span>
          <span><a class="btn btn-outline-primary" href="{% url 'logout'%}?next={{request.path}}" role="button">Logout</a></span>
        </div>
      {% else %}
        <a class="btn btn-outline-success" href="{% url 'login'%}?next={{request.path}}" role="button">Login</a>  
      {% endif %}
    </div>
    </nav>
    <main class="container bg-dark">
      <div class="jumbotron">
        {% block content %}{% endblock %}
        {% block pagination %}
        {% load searchfilter %}
          {% if is_paginated %}
          	<div class="text-center">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</div>
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="{{ request.path }}?detail={{ request.GET.detail }}&section={{ request.GET.section }}&line={{ request.GET.line }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
              {% endif %}
              {% for page in page_obj.number|pagerange:page_obj.paginator.num_pages%}
              	{% ifequal page page_obj.number %}
          			<li class="page-item active"><a class="page-link" href="#">{{page}}</a></li>
          		{% else %}
          			<li class="page-item"><a class="page-link" href="{{ request.path }}?detail={{ request.GET.detail }}&section={{ request.GET.section }}&line={{ request.GET.line }}&page={{ page }}">{{page}}</a></li>
          		{% endifequal %}
          	  {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{{ request.path }}?detail={{ request.GET.detail }}&section={{ request.GET.section }}&line={{ request.GET.line }}&page={{ page_obj.next_page_number }}">Next</a></li>
              {% endif %}
            </ul>
          {% endif %}
        {% endblock %}
      </div>
    </main>
    <footer>
      <div class="footer navbar-fixed-bottom text-right">
        {% if user.is_authenticated %}
          <p><a class="text-warning text-capitalize">User: {{ user.get_username }}</a></p>
        {% endif %}
        <p id="datetime" class="text-success"></p>
      </div>
    </footer>
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript">
  function startTime() {
    var today = new Date();
    var month = today.getMonth() + 1;
    var day = today.getDate();
    var year = today.getFullYear();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    month = checkTime(month);
    day = checkTime(day);
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('datetime').innerHTML =
    month + "/" + day + "/" + year + " " + h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
  }
  function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
  }
</script>
</body>
</html>

partserver/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Parts Management System</h1>
  <div class="container border border-success px-auto py-2 my-2">
  	<span class="text-center"><h4>Parts Search</h4></span>
  	<form class="form-horizontal" action="{% url 'partserver:parts' %}" method="get">
  		<div class="form-group">
  			<label>Line:</label>
			<select class="form-control" name="line">
				<option value=""></option>
			{% for line in line_list %}
  				<option value={{ line.id }}>{{ line.name }}</option>
  			{% endfor %}
			</select>
		</div>
		<div class="form-group">
			<label>Section:</label>
			<select class="form-control" name="section">
				<option value=""></option>
			{% for section in section_list %}
	  			<option value={{ section.id }}>{{ section.name }}</option>
	  		{% endfor %}
			</select>
		</div>
		<div class="form-group">
			<label>Keyword (<i>e.g. part's name or material number</i>):</label>
    		<input class="form-control" name="detail" type="text" placeholder="Search parts by key word or parts number">
    	</div>
    	<div class="form-group">
    		<input class="btn btn-success form-control" type="submit" value="Search">
    	</div>
  	</form>
  </div>
  <div class="container border border-success px-auto py-2">
  	<span class="text-center"><h4>Line Pictures</h4></span>
  	<div class="container">
	  <div class="row">
	  	{% for line in line_list %}
	  		{% if line.name != "General" %}
	    		<div class="col"><a class="btn btn-info btn-lg btn-block m-1" href="{{ line.get_absolute_url }}">{{line.name}}</a></div>
	    	{% endif %}
	    {% endfor %}
	  </div>
	</div>
  </div>
{% endblock %}