maint/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('partserver/', include('partserver.urls')),
    path('', RedirectView.as_view(url='partserver/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partserver/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'partserver'
urlpatterns = [
	path('', views.index, name='index'),
	path('lines/<int:pk>', views.LineDetailView.as_view(), name='line-detail'),
	path('parts/', views.PartListView.as_view(), name='parts'),
	path('parts/<int:pk>', views.PartDetailView.as_view(), name='part-detail'),
	path('part/create/', views.PartCreate.as_view(), name='part_create'),
    path('part/<int:pk>/update/', views.PartUpdate.as_view(), name='part_update'),
    path('part/<int:pk>/delete/', views.PartDelete.as_view(), name='part_delete'),
    path('schematics/', views.SchematicListView.as_view(), name='schematics'),
	path('schematic/create/', views.SchematicCreate.as_view(), name='schematic_create'),
	path('schematic/<int:pk>/update/', views.SchematicUpdate.as_view(), name='schematic_update'),
	path('schematic/<int:pk>/delete/', views.SchematicDelete.as_view(), name='schematic_delete'),
	path('manuals/', views.ManualListView.as_view(), name='manuals'),
	path('manual/create/', views.ManualCreate.as_view(), name='manual_create'),
	path('manual/<int:pk>/update/', views.ManualUpdate.as_view(), name='manual_update'),
	path('manual/<int:pk>/delete/', views.ManualDelete.as_view(), name='manual_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partserver/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.template.defaultfilters import slugify
import uuid
from django.db.models.signals import post_delete
from django.dispatch import receiver
from .validators import validate_file_extension
import os

def get_image_filename(instance, filename):
    name = instance.part.name
    slug = slugify(name)
    return "part_images/%s-%s" % (slug, filename)  

def get_schematic_filename(instance, filename):
	name = instance.name
	line = instance.line.name
	section = instance.section.name
	slug = slugify(name)
	ext = os.path.splitext(filename)[1]
	return "schematics/%s/%s/%s%s" % (line, section, slug, ext)

def get_manual_filename(instance, filename):
	name = instance.name
	line = instance.line.name
	section = instance.section.name
	slug = slugify(name)
	ext = os.path.splitext(filename)[1]
	return "manual/%s/%s/%s%s" % (line, section, slug, ext)

class Section(models.Model):
	"""Model representing the section of line."""
	name = models.CharField(max_length=30, help_text='Enter the section for the line')

	def __str__(self):
		"""String for representing the Model object."""
		return self.name

class Part(models.Model):
	#module representing the part
	name = models.CharField(max_length=100, help_text='Enter the part\'s name')
	number = models.CharField(max_length=20, help_text='Enter the part\'s number')
	quantity = models.PositiveIntegerField(blank=True, null=True, help_text='Part\'s in stock quantity')
	specs = models.TextField(max_length=1000, help_text='Enter the specification of the part')
	lines = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied lines for the part')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section(s) for this part')

	class Meta:
		ordering = ['name']

	def __str__(self):
		"""String for representing the Model object."""
		return self.name + " - " + self.number
    
	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('partserver:part-detail', args=[str(self.id)])

	def get_images(request):
		images = PartImages.objects.filter(part=request).values_list('images', flat=True)
		return images

	def get_specs(self):
		return self.specs.split("\n")

class Schematic(models.Model):
	name = models.CharField(max_length=100, help_text='Enter the schematic\'s name')
	line = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied line for the schematic')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section for the schematic')
	pdfFile = models.FileField(upload_to=get_schematic_filename, validators=[validate_file_extension])

class Manual(models.Model):
	name = models.CharField(max_length=100, help_text='Enter the manual\'s name')
	line = models.ForeignKey('Line', on_delete=models.SET_NULL, null=True, help_text='Select the applied line for the manual')
	section = models.ForeignKey(Section, on_delete=models.CASCADE, null=False, help_text='Select the section for the manual')
	pdfFile = models.FileField(upload_to=get_manual_filename, validators=[validate_file_extension])


class Line(models.Model):
	#name for the line(s)
	name = models.CharField(max_length=50, help_text='Enter the line(s)')
	section = models.ManyToManyField(Section, help_text='Select the section(s) for this line')

	class Meta:
		ordering = ['id']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('partserver:line-detail', args=[str(self.id)])

	def display_section(self):
		"""Create a string for the Section in Admin."""
		return ', '.join(section.name for section in self.section.all())

class PartImages(models.Model):
    """Images for a model"""
    part = models.ForeignKey(
        Part,
        null=False,
        on_delete=models.CASCADE,
        related_name='images',
        )

    images = models.ImageField(
        verbose_name='images',
        upload_to=get_image_filename,
    )

@receiver(post_delete, sender=PartImages)
def submission_delete(sender, instance, **kwargs):
    instance.images.delete(False) 

@receiver(post_delete, sender=Schematic)
def submission_delete(sender, instance, **kwargs):
    instance.pdfFile.delete(False) 

@receiver(post_delete, sender=Manual)
def submission_delete(sender, instance, **kwargs):
    instance.pdfFile.delete(False) 

partserver/views.py
from django.shortcuts import render
from .models import Part, Section, Line, PartImages, Schematic, Manual
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import qrcode
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory
from django.db.models import Q

def index(request):
	"""View function for home page of site."""

	# Generate counts of some of the main objects
	part_list = Part.objects.all()
	num_parts = part_list.count()
	line_list = Line.objects.all()
	section_list = Section.objects.all()
	context = {
		'num_parts': num_parts,
		'line_list': line_list,
		'section_list': section_list,
	}

	# Render the HTML template index.html with the data in the context variable
	return render(request, 'index.html', context=context)

class LineDetailView(generic.DetailView):
	model = Line
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(LineDetailView, self).get_context_data(**kwargs)
		context['part_list'] = Part.objects.all()
		return context

class PartListView(generic.ListView):
	model = Part
	paginate_by = 30
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(PartListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		context['section_list'] = Section.objects.all()
		context['num_parts'] = self.get_queryset().count()
		return context
	def get_queryset(self):
		querydetail = self.request.GET.get('detail')
		querysection = self.request.GET.get('section')
		queryline = self.request.GET.get('line')
		FilteredParts = Part.objects.all()
		if queryline:
			FilteredParts = Part.objects.filter(lines=Line.objects.get(pk=queryline))
		if querysection:	
			FilteredParts = FilteredParts.filter(section=Section.objects.get(id=querysection))
		FilteredParts = FilteredParts.filter(Q(name__icontains=querydetail) |
								   Q(number__icontains=querydetail) | 
								   Q(specs__icontains=querydetail))
		

		return FilteredParts

class PartDetailView(generic.DetailView):
	model = Part
	def part_detail_view(request, primary_key):
		try:
			part = part.objects.get(pk=primary_key)

		except Part.DoesNotExist:
			raise Http404('Part does not exist')

		return render(request, 'partserver/part_detail.html', context={'part': part})

class SchematicListView(generic.ListView):
	model = Schematic
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(SchematicListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		return context

class ManualListView(generic.ListView):
	model = Manual
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get the context
		context = super(ManualListView, self).get_context_data(**kwargs)
		context['line_list'] = Line.objects.all()
		return context

class PartImagesInline(InlineFormSetFactory):
	model = PartImages
	fields = '__all__'

class PartCreate(LoginRequiredMixin, CreateWithInlinesView):
	model = Part
	inlines = [PartImagesInline]
	fields = ['name', 'number', 'specs', 'lines', 'section']

class PartUpdate(LoginRequiredMixin, UpdateWithInlinesView):
	model = Part
	inlines = [PartImagesInline]
	fields = ['name', 'number', 'specs', 'lines', 'section']

class PartDelete(LoginRequiredMixin, DeleteView):
	model = Part
	success_url = reverse_lazy('index')

class SchematicCreate(LoginRequiredMixin, CreateView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class SchematicUpdate(LoginRequiredMixin, UpdateView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class SchematicDelete(LoginRequiredMixin, DeleteView):
	model = Schematic
	fields = '__all__'
	success_url = reverse_lazy('partserver:schematics')

class ManualCreate(LoginRequiredMixin, CreateView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

class ManualUpdate(LoginRequiredMixin, UpdateView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

class ManualDelete(LoginRequiredMixin, DeleteView):
	model = Manual
	fields = '__all__'
	success_url = reverse_lazy('partserver:manuals')

partserver/templates/partserver/manual_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Manual</h1>

<p>Are you sure you want to delete the manual: {{ manual }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

partserver/templates/partserver/manual_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if "update" in request.path %}
	<h3>Manual Update</h3>
{% else %}
	<h3>Manual Upload</h3>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table required>
    {{ form.as_table }}
    {% for formset in inlines %}
    	{{ formset }}
  	{% endfor %}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

partserver/templates/partserver/manual_list.html
{% extends "base_generic.html" %}

{% block content %}
{% load pdffilter %}
  <h1>Manual</h1>
  <div class="text-muted">
    Clicked the specific line!
  </div>
  {% if line_list %}
  <div>
    {% for line in line_list %}
      {% if line.name != "General" %}
        <details>
          <summary><h4 class="list-group-item list-group-item-action">{{line}}</h4></summary>
          {% for section in line.section.all %}
            <details>
              <summary><div class="btn btn-primary btn-block btn-md my-1">{{section}}</div></summary>
              {% for manual in manual_list|linefilter:line|sectionfilter:section %}
                <button type="button" class="btn btn-success btn-block btn-sm my-1" data-toggle="modal" data-target="#manualModal" onclick="manualPopup('{{ manual.name }}', '{{ manual.pdfFile.url }}', '{{ manual.pk }}')">
                  {{ manual.name }}
                </button>
              {% endfor %}
            </details>
          {% endfor %}
        </details>
      {% endif %}
    {% endfor %}
  </div>
  <div>
  </div>
  {% else %}
    <p>There are no line in the library.</p>
  {% endif %}
  <div class="modal fade" id="manualModal" tabindex="-1" role="dialog" aria-labelledby="manualModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="manualModalLabel"></h5>
          <a id="downloadQR" class="btn btn-success ml-1">Download QR code</a>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <a href="#" download="manual.png"><img class="img-fluid mx-auto w-50" id="pdfQR"></img></a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          {% if user.is_authenticated %}
            <a id="manualDelete" class="btn btn-warning" href="{% url 'partserver:manual_delete' 99999 %}">Delete</a>
            <a id="manualUpdate" class="btn btn-warning" href="{% url 'partserver:manual_update' 99999 %}">Update</a>
          {% endif %}
          <a id="modalPDFOpen" class="btn btn-success" href="" target="_new">Open PDF</a>
        </div>
      </div>
    </div>
  </div>
  {% load static %}
  <script type="text/javascript">
    function manualPopup(modalLabel, pdfUrl, manualPK) {
      var manualUpdateButton = document.getElementById("manualUpdate");
      var manualDeleteButton = document.getElementById("manualDelete");
      if(manualUpdateButton) {
        var updateUrl = String(manualUpdateButton.href).replace("99999", manualPK);
        manualUpdateButton.href = updateUrl;
      }
      if(manualDeleteButton) {
        var deleteUrl = String(manualDeleteButton.href).replace("99999", manualPK);
        manualDeleteButton.href = deleteUrl;
      }
      document.getElementById("manualModalLabel").innerHTML = modalLabel;
      document.getElementById("modalPDFOpen").href = pdfUrl;
      var domainUrl = String(location.href).split("/")[2];
      var qr = new QRious({
        element: document.getElementById('pdfQR'),
        value: "http://" + domainUrl + pdfUrl,
          mime: 'image/jpg',
          size: 1920
      });
      document.getElementById('downloadQR').download = modalLabel + ".png";
      document.getElementById('downloadQR').href = qr.toDataURL();
    }
  </script> 
{% endblock %}

partserver/templates/partserver/part_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Part</h1>

<p>Are you sure you want to delete the part: {{ part }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

partserver/templates/partserver/part_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="container-fluid">
    <h1 id=part_name>
      {{ part.name }}
    </h1>
    <form class="form-horizontal" action="{% url 'partserver:parts' %}" method="get">
      <div class="form-group">
        <input name="detail" type="hidden" value="">
        <input name="section" type="hidden" value={{part.section.id}}>
        <input name="line" type="hidden" value={{part.lines.id}}>
      </div>
      <div class="form-group">
        <input class="btn btn-light btn-lg text-primary font-weight-bold" type="submit" value="{{ part.lines }} {{ part.section}}">
        <a id="downloadQR" class="btn btn-lg btn-success ml-1">Download QR code</a>
      </div>
    </form>
    <div class="row">
      <div class="col-md">
        <div id="carouselExampleControls" class="carousel slide bg-secondary" data-ride="carousel">
          <div class="carousel-inner">

            {% if part.get_images %}
              {% for image in part.get_images %}
              <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
              <a data-toggle="modal" data-target="#exampleModal">
                <img class="mx-auto d-block w-75" src="/media/{{ image }}" alt="{{ img }}" onclick="ModalImg(this)">
              </a>
              </div>
              {% endfor %}
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            {% else %}
              <div class="carousel-item active">
                <img class="mx-auto d-block w-75" src="/media/part_images/noimage.png" alt="There is no image uploaded yet." onclick="ModalImg(this)">
              </div>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col-md">
        <div class="col">
          <div class="col-sm">
            <div class="row">
              <div class="col-sm">
                <p><strong>Line:</strong></p>
              </div>
              <div class="col-sm">
                <p id="part_line">{{ part.lines }}</p>
              </div>
            </div>
          </div>
          <div class="col-sm">
            <div class="row">
              <div class="col-sm">
                <p><strong>Material Number:</strong></p>
              </div>
              <div class="col-sm">
                <p id="part_number">{{ part.number }}</p>
              </div>
            </div>
          </div>
          <div class="col-sm">
              <div class="row">
              <div class="col-sm">
                <p><strong>Specsifications:</strong></p>
              </div>
              <div class="col-sm">
                <p id="part_specs">
                  {% for specLine in part.get_specs %}
                    {{specLine}}
                    <br>
                  {% endfor %}
                </p>
              </div>
            </div>
          </div>
          {% if part.quantity >= 0 %}
          <div class="col-sm">
              <div class="row">
              <div class="col-sm">
                <p><strong>In Stock:</strong></p>
              </div>
              <div class="col-sm">
                <p id="part_quantity">{{ part.quantity }}</p>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
		<div class="container-fluid">
      <img class="img-fluid mx-auto w-50" id="qr"></img>
    </div>
        {% if user.is_authenticated %}
        <!--
        <div class="mt-1 p-0 btn btn-dark float-right">
          <a class="nav-link text-warning font-weight-bold" href="{% url 'partserver:part_delete' part.pk %}">Delete</a>
        </div>
      -->
        <div class="mt-1 p-0 btn btn-dark mr-2 float-right">
          <a class="nav-link text-warning font-weight-bold" href="{% url 'partserver:part_update' part.pk %}?next={{request.path}}">Update</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img id="modal_img" class="mx-auto d-block w-100" src="">
          </div>
        </div>
      </div>
  </div> 
  <script type="text/javascript">
  	var qr = new QRious({
      	element: document.getElementById('qr'),
       	value: location.href,
        	mime: 'image/png',
        	size: 1920
  	})
    document.getElementById('downloadQR').download = document.querySelector("#part_number").textContent.trim() + ".png";
    document.getElementById('downloadQR').href = qr.toDataURL();

    function ModalImg (img) {
      document.getElementById("modal_img").src = img.src;
    }
  </script> 
{% endblock %}

partserver/templates/partserver/part_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if "update" in request.path %}
	<h3>Part Update</h3>
{% else %}
	<h3>Part Create</h3>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table required>
    {{ form.as_table }}
    {% for formset in inlines %}
    	{{ formset }}
  	{% endfor %}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

partserver/templates/partserver/part_list.html
 {% extends "base_generic.html" %}

{% block content %}
{% load searchfilter %}
  <h1>Parts</h1>
  <p>
  {% if request.GET.line or request.GET.section %}
    Result on <b>{{ request.GET.line|idtoname:line_list }} {{ request.GET.section|idtoname:section_list }}</b><br>
  {% endif %}
  {% if request.GET.detail %}
    Key word: <b>{{ request.GET.detail }}</b><br>
  {% endif %}
  {% if num_parts > 1%}
    <i>There are {{num_parts}} parts in the result.</i>
  {% elif num_parts %}
    <i>There is {{num_parts}} part in the result.</i>
  {% endif %}
  </p>

  <div class="container border border-success px-auto py-2 my-2">
    <details>
    <summary><h4 class="btn btn-primary btn-block">Click to expand search function</h4></summary>
    <form class="form-horizontal" action="{% url 'partserver:parts' %}" method="get">
      <div class="form-group">
        <label>Line:</label>
      <select class="form-control" name="line">
        <option value=""></option>
        {% for line in line_list %}
          {% if line.id|idcompare:request.GET.line %}
            <option selected="selected" value={{ line.id }}>{{ line.name }}</option>
          {% else %}
            <option value={{ line.id }}>{{ line.name }}</option>
          {% endif %}
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label>Section:</label>
      <select class="form-control" name="section">
        <option value=""></option>
        {% for section in section_list %}
          {% if section.id|idcompare:request.GET.section %}
            <option selected="selected" value={{ section.id }}>{{ section.name }}</option>
          {% else %}
            <option value={{ section.id }}>{{ section.name }}</option>
          {% endif %}
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label>Keyword (<i>e.g. part's name or material number</i>):</label>
        <input class="form-control" name="detail" type="text" placeholder="Search parts by key word or parts number">
      </div>
      <div class="form-group">
        <input class="btn btn-success right form-control" type="submit" value="Search">
      </div>
    </form>
    </details>
  </div>
  {% if part_list %}
  <div id="parts_list">
    {% for part in part_list %}<a class='list-group-item list-group-item-action' href='{{ part.get_absolute_url }}'>{{part.name}} ({{part.lines}})</a>{% endfor %}
  </div>
  {% else %}
    <p>There are no parts in the result.</p>
  {% endif %}   
{% endblock %}

partserver/templates/partserver/schematic_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Schematic</h1>

<p>Are you sure you want to delete the schematic: {{ schematic }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

partserver/templates/partserver/schematic_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if "update" in request.path %}
	<h3>Schematic Update</h3>
{% else %}
	<h3>Schematic Upload</h3>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table required>
    {{ form.as_table }}
    {% for formset in inlines %}
    	{{ formset }}
  	{% endfor %}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

partserver/templates/partserver/schematic_list.html
{% extends "base_generic.html" %}

{% block content %}
{% load pdffilter %}
  <h1>Schematic</h1>
  <div class="text-muted">
    Clicked the specific line!
  </div>
  {% if line_list %}
  <div>
    {% for line in line_list %}
      {% if line.name != "General" %}
        <details>
          <summary><h4 class="list-group-item list-group-item-action">{{line}}</h4></summary>
          {% for section in line.section.all %}
          <details>
            <summary><div class="btn btn-primary btn-block btn-md my-1">{{section}}</div></summary>
            {% for schematic in schematic_list|linefilter:line|sectionfilter:section %}
              <button type="button" class="btn btn-success btn-block btn-sm my-1" data-toggle="modal" data-target="#schematicModal" onclick="schematicPopup('{{ schematic.name }}', '{{ schematic.pdfFile.url }}', '{{ schematic.pk }}')">
                {{ schematic.name }}
              </button>
            {% endfor %}
          </details>
          {% endfor %}
        </details>
      {% endif %}
    {% endfor %}
  </div>
  <div>
  </div>
  {% else %}
    <p>There are no line in the library.</p>
  {% endif %}
  <div class="modal fade" id="schematicModal" tabindex="-1" role="dialog" aria-labelledby="schematicModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="schematicModalLabel"></h5>
          <a id="downloadQR" class="btn btn-success ml-1">Download QR code</a>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <img class="img-fluid mx-auto w-50" id="pdfQR"></img>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          {% if user.is_authenticated %}
            <a id="schematicDelete" class="btn btn-warning" href="{% url 'partserver:schematic_delete' 99999 %}">Delete</a>
            <a id="schematicUpdate" class="btn btn-warning" href="{% url 'partserver:schematic_update' 99999 %}">Update</a>
          {% endif %}
          <a id="modalPDFOpen" class="btn btn-success" href="" target="_new">Open PDF</a>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    function schematicPopup(modalLabel, pdfUrl, schematicPK) {
      var schematicUpdateButton = document.getElementById("schematicUpdate");
      var schematicDeleteButton = document.getElementById("schematicDelete");
      if(schematicUpdateButton) {
        var updateUrl = String(schematicUpdateButton.href).replace("99999", schematicPK);
        schematicUpdateButton.href = updateUrl;
      }
      if(schematicDeleteButton) {
        var deleteUrl = String(schematicDeleteButton.href).replace("99999", schematicPK);
        schematicDeleteButton.href = deleteUrl;
      }
      document.getElementById("schematicModalLabel").innerHTML = modalLabel;
      document.getElementById("modalPDFOpen").href = pdfUrl;
      var domainUrl = String(location.href).split("/")[2];
      var qr = new QRious({
        element: document.getElementById('pdfQR'),
        value: "http://" + domainUrl + pdfUrl,
          mime: 'image/jpg',
          size: 1920
      });
      document.getElementById('downloadQR').download = modalLabel + ".png";
      document.getElementById('downloadQR').href = qr.toDataURL();
    }
  </script> 
{% endblock %}